version: "3.3"

networks: 
  django-asa-network:    
    ipam:
      config:
        - subnet: 172.30.0.0/24

services: 
  django_app:
    build: .
    container_name: django_app_production
    ports:
      - '5000:5000'
    networks:
      django-asa-network:
        ipv4_address: 172.30.0.5
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "load.py"]
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "banco123"
    ports:
      - "5432:5432"

    networks:
      django-asa-network:
        ipv4_address: 172.30.0.6