# Generated by Django 3.2.2 on 2021-05-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assentos', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0.0)),
                ('data', models.DateTimeField()),
                ('idAeroportoDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_aeroporto_destino', to='sistema.aeroporto')),
                ('idAeroportoOrigem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voo_aeroporto_origem', to='sistema.aeroporto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('cancelada', models.BooleanField(default=False)),
                ('eticket', models.CharField(default='', max_length=100)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idVoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.voo')),
            ],
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='idCidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cidade'),
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAeroportoDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_aeroporto_destino', to='sistema.aeroporto')),
                ('idAeroportoOrigem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_aeroporto_origem', to='sistema.aeroporto')),
            ],
            options={
                'unique_together': {('idAeroportoOrigem', 'idAeroportoDestino')},
            },
        ),
    ]
